language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    # Spark 1.4.1
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="1.4.1" LUCENE_ANALYZER="en"
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.4.1" LUCENE_ANALYZER="en"
    # Spark 1.5.2
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="1.5.2" LUCENE_ANALYZER="en"
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.5.2" LUCENE_ANALYZER="en"
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.5.2" LUCENE_ANALYZER="en"
    # Spark 1.6.1
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="1.6.2" LUCENE_ANALYZER="en"
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.6.2" LUCENE_ANALYZER="en"
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.6.2" LUCENE_ANALYZER="en"
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.6.2" LUCENE_ANALYZER="whitespace"
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update coverage -Dlucenerdd.analyzer.name=${LUCENE_ANALYZER} -test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION assembly
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
after_success: "sbt coverage test coverageReport coveralls"

