cache: false
language: scala
scala:
  - "2.10.6"
  - "2.11.8"
jdk:
  - oraclejdk7
  - openjdk7

script: "sbt ++$TRAVIS_SCALA_VERSION clean update coverage test"
after_success: "sbt coverageReport coveralls"

