language: scala
scala:
  - "2.10.6"
  - "2.11.8"
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script: "sbt clean update +assembly && sbt clean coverage test"
after_success: "sbt coverageReport coveralls"

